version: "3.1"

services:
  node-app:
    image: node-app:1.1
    container_name: node-app
    restart: always
    ports:
      - 3000:3000
    networks:
      - mongo-compose-network
    depends_on:
      - mongodb-server

  mongodb-server:
    image: mongo:latest
    container_name: mongodb-server
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mongo-login
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb-server
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: password

    networks:
      - mongo-compose-network
    depends_on:
      - mongodb-server

networks:
  mongo-compose-network:
    driver: bridge

volumes:
  mongodb_data_container:
